spring.application.name=practiceProject
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=artist-reviewer
razorpay.key.id=rzp_test_xxxxxxxxx
razorpay.key.secret=xxxxxxxxxxxx